#!/usr/bin/env bash
#This will Check if the log file exists

log_file="apache-access.log"
if [ -e "$log_file" ]; then

    awk '{print $1, $9}' "$log_file"
else
    echo "The log file $log_file does not exist."
fi
