#!/usr/bin/env bash
# This script loops from 1 to 10 and displays special messages for 4th and 8th iterations using while loop and conditional statements

count=1
while [ "$count" -le 10 ]
do
  if [ "$count" -eq 4 ]; then
    echo "bad luck"
  elif [ "$count" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done

